# Generated by Django 5.1.7 on 2025-03-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
